cd acceptance-timing
grunt deploy
cd ..
cd defect-density-dashboard
grunt deploy
cd ..
cd defect-trend-dashboard
grunt deploy
cd ..
cd delivery-acceleration-dashboard
grunt deploy
cd ..
cd delivery-efficiency-per-task-type
grunt deploy
cd ..
cd delivery-effort-focus-dashboard
grunt deploy
cd ..
cd delivery-effort-task-hours
grunt deploy
cd ..
cd estimation-effort
grunt deploy
cd ..
cd integrity-dashboard
grunt deploy
cd ..
cd oi-backlog-maturity
grunt deploy
cd ..
cd oi-common
grunt deploy
cd ..
cd oi-predictability
grunt deploy
cd ..
cd oi-productivity
grunt deploy
cd ..
cd oi-quality
grunt deploy
cd ..
cd predictability-dashboard
grunt deploy
cd ..
cd productivity-dashboard
grunt deploy
cd ..
cd productivity-throughput
grunt deploy
cd ..
cd productivity-velocity
grunt deploy
cd ..
cd quality-defects-found
grunt deploy
cd ..
cd quarter-selector
grunt deploy
cd ..
cd release-burnup
grunt deploy
cd ..
cd responsiveness-time-in-process
grunt deploy
cd ..
cd split-story-dashboard
grunt deploy
cd ..
cd utilization-updated
grunt deploy
cd ..
cd validation-dashboard
grunt deploy
cd ..
cd variability-throughput-stories
grunt deploy
cd ..